Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "soa-calc-server"
  config.vm.network "forwarded_port", guest: 8000, host: 8001
  config.vm.synced_folder "../calculator_api", "/home/vagrant/app"
  config.vm.provision "shell", path: "provision.sh"
end
